// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseCard: typeof import('./src/components/UI/BaseCard.vue')['default']
    BaseFilter: typeof import('./src/components/UI/BaseFilter.vue')['default']
    BaseSearch: typeof import('./src/components/UI/BaseSearch.vue')['default']
    CountryList: typeof import('./src/components/pages/CountryList.vue')['default']
    HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"]
    TheHeader: typeof import('./src/components/Layout/TheHeader.vue')['default']
  }
}
